"""Generate TeX numbers and tables exclusively from validated aggregates."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ..aggregate import read_aggregate
from ..plotting import DOMAIN_ORDER, DOMAIN_TITLES

_GRADE_ORDER = {"A": 3, "B": 2, "C": 1, "insufficient": 0}
_PREFERRED_FAMILY = {
    "transformer": "learned_decoder",
    "diffusion": "learned_score",
    "reinforcement": "learned_policy",
    "multiagent": "learned_agents",
}


def _command(name: str, value: Any) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def _tex_name(domain: str) -> str:
    return {
        "transformer": "Transformer",
        "diffusion": "Diffusion",
        "reinforcement": "RL",
        "multiagent": "Multiagent",
    }[domain]


def _escape(value: str) -> str:
    return value.replace("_", "\\_")


def write_paper_results(
    aggregate: dict[str, Any] | str | Path,
    output_path: str | Path,
) -> Path:
    data = read_aggregate(aggregate) if isinstance(aggregate, (str, Path)) else aggregate
    lines = [
        "% Generated by statphys.continuation.paper; do not edit.",
        _command("ResultsReady", 1),
        _command("NumSeeds", int(data["required_seed_count"])),
        _command("NumRegisteredRuns", int(data["registered_runs"])),
        _command("NumCompletedRuns", int(data["completed_runs"])),
        _command("NumConditions", len(data["records"])),
        _command("NumFamilies", len({(item["domain"], item.get("family", "anchor")) for item in data["records"]})),
        _command(
            "NumTierBPlusConditions",
            sum(item.get("parameters", {}).get("fidelity_tier") == "B+" for item in data["records"]),
        ),
    ]
    table_rows: list[str] = []
    for domain in DOMAIN_ORDER:
        records = [item for item in data["records"] if item["domain"] == domain]
        if not records:
            continue
        preferred = _PREFERRED_FAMILY[domain]
        family = preferred if any(item.get("family") == preferred for item in records) else sorted(
            {item.get("family", "anchor") for item in records}
        )[0]
        family_records = [item for item in records if item.get("family", "anchor") == family]
        representative = sorted({item["variant"] for item in family_records})[0]
        selected = [item for item in family_records if item["variant"] == representative]
        largest = max(int(item["size"]) for item in selected)
        selected = [item for item in selected if int(item["size"]) == largest]
        peak = max(selected, key=lambda item: float(item["metrics"]["susceptibility"]["mean"]))
        interval = peak["metrics"]["order_parameter"]
        evidence = [
            item
            for item in data.get("evidence", [])
            if item["domain"] == domain
            and item.get("family", "anchor") == family
            and item["variant"] == representative
        ]
        grade = max(
            (item["grade"] for item in evidence),
            key=lambda value: _GRADE_ORDER.get(value, -1),
            default="insufficient",
        )
        prefix = _tex_name(domain)
        lines.extend(
            (
                _command(f"{prefix}Representative", _escape(representative)),
                _command(f"{prefix}LargestSize", largest),
                _command(f"{prefix}PeakControl", f"{float(peak['control']):.4g}"),
                _command(f"{prefix}PeakOrder", f"{float(interval['mean']):.4g}"),
                _command(f"{prefix}PeakOrderCI", f"{float(interval['ci95']):.3g}"),
                _command(f"{prefix}EvidenceGrade", grade),
            )
        )
        table_rows.append(
            f"{DOMAIN_TITLES[domain]} & {_escape(family)} & {_escape(representative)} & {largest} "
            f"& {float(peak['control']):.4g} "
            f"& \\({float(interval['mean']):.3f}\\pm{float(interval['ci95']):.3f}\\) "
            f"& {grade} \\\\"
        )
    lines.extend(("", "\\newcommand{\\ContinuationResultsRows}{%", *table_rows, "}"))
    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text("\n".join(lines) + "\n")
    temporary.replace(target)
    return target


__all__ = ["write_paper_results"]
